(function(){
'use strict';
const DB=window.M68DB;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=(p='id')=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const dayKey=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const fmtDate=(s,opt={weekday:'long',day:'numeric',month:'long'})=>new Intl.DateTimeFormat('en-IN',opt).format(new Date(s+'T12:00:00'));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const num=(v,d=0)=>Number.isFinite(+v)?+v:d;
let state={view:'today',foods:[],exercises:[],mealTemplates:[],workoutTemplates:[],logs:[],weights:[],strength:[],settings:null};
const defaults={id:'main',name:'Sourav',startWeight:87,goalWeight:68,heightCm:170,kcalTarget:1640,proteinTarget:88,waterTargetMl:3000,startDate:dayKey(),weeklyLossTarget:.5,theme:'light'};
const seedFoods=[
 ['Boiled egg, whole','piece',77.5,6.5,0.5,5.5],['Egg white, boiled','piece',17,3.5,0.2,0],['Roti, no oil','piece',105,3.5,20,1],['Cooked rice','100 g',130,2.7,28,0.3],['Mixed salad','100 g',30,1,6,0.2],['Guava','100 g',58,2.6,14,1],['Dal, cooked','100 ml',83,4.7,14,1.2],['Fish curry, lean fish','100 g',150,20,3,6],['Chicken curry, skinless','100 g',165,20,3,7],['Plain curd','100 g',65,4,5,3],['Mixed vegetable curry','100 g',80,2,10,3.5],['Paneer','100 g',265,18,6,20]
].map(x=>({id:uid('food'),name:x[0],unit:x[1],kcal:x[2],protein:x[3],carbs:x[4],fat:x[5],favorite:false}));
const seedExercises=[
 ['Goblet squat','Dumbbell','Strength','kg'],['Dumbbell floor press','Dumbbell','Strength','kg'],['One-arm dumbbell row','Dumbbell','Strength','kg'],['Dumbbell Romanian deadlift','Dumbbell','Strength','kg'],['Standing calf raise','Dumbbell','Strength','kg'],['Reverse lunge','Bodyweight','Strength','reps'],['Barbell overhead press','Barbell','Strength','kg'],['Barbell bent-over row','Barbell','Strength','kg'],['Barbell glute bridge','Barbell','Strength','kg'],['Barbell biceps curl','Barbell','Strength','kg'],['Plank','Bodyweight','Core','seconds'],['Bird-dog','Bodyweight','Mobility','reps'],['Brisk walk','None','Cardio','minutes']
].map(x=>({id:uid('ex'),name:x[0],equipment:x[1],category:x[2],loadUnit:x[3],favorite:false}));
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openSheet(html){$('#sheetContent').innerHTML=html;$('#overlay').hidden=false;$('#sheet').hidden=false;document.body.style.overflow='hidden'}
function closeSheet(){ $('#overlay').hidden=true;$('#sheet').hidden=true;document.body.style.overflow=''; }
async function boot(){
  await seed(); await loadAll(); migrateV2(); bindShell(); render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
async function seed(){
  if(!(await DB.get('settings','main'))) await DB.put('settings',defaults);
  if((await DB.all('foods')).length===0) await DB.bulkPut('foods',seedFoods);
  if((await DB.all('exercises')).length===0) await DB.bulkPut('exercises',seedExercises);
  if((await DB.all('mealTemplates')).length===0){
    const f=seedFoods, get=n=>f.find(x=>x.name===n)?.id;
    await DB.bulkPut('mealTemplates',[
      {id:uid('meal'),name:'Breakfast',time:'08:30',items:[{foodId:get('Boiled egg, whole'),qty:2},{foodId:get('Egg white, boiled'),qty:2},{foodId:get('Roti, no oil'),qty:1},{foodId:get('Mixed salad'),qty:1.5}]},
      {id:uid('meal'),name:'Lunch',time:'13:30',items:[{foodId:get('Cooked rice'),qty:1.5},{foodId:get('Dal, cooked'),qty:1.5},{foodId:get('Fish curry, lean fish'),qty:.6},{foodId:get('Mixed vegetable curry'),qty:1.5},{foodId:get('Mixed salad'),qty:1.5}]},
      {id:uid('meal'),name:'Dinner',time:'20:00',items:[{foodId:get('Cooked rice'),qty:1.5},{foodId:get('Chicken curry, skinless'),qty:1},{foodId:get('Mixed vegetable curry'),qty:1.5},{foodId:get('Mixed salad'),qty:1.5}]}
    ]);
  }
  if((await DB.all('workoutTemplates')).length===0){
    const e=seedExercises, get=n=>e.find(x=>x.name===n)?.id;
    await DB.bulkPut('workoutTemplates',[
      {id:uid('workout'),name:'Full body A',days:[2,6],items:[['Goblet squat',3,10,9.1],['Dumbbell floor press',3,8,18.2],['One-arm dumbbell row',3,10,9.1],['Dumbbell Romanian deadlift',3,10,18.2],['Plank',2,30,0]].map(x=>({exerciseId:get(x[0]),sets:x[1],reps:x[2],load:x[3]}))},
      {id:uid('workout'),name:'Full body B',days:[4],items:[['Reverse lunge',3,8,0],['Barbell overhead press',3,8,9.1],['Barbell bent-over row',3,12,9.1],['Barbell glute bridge',3,12,9.1],['Barbell biceps curl',2,10,9.1]].map(x=>({exerciseId:get(x[0]),sets:x[1],reps:x[2],load:x[3]}))}
    ]);
  }
}
async function loadAll(){
  const [foods,exercises,mealTemplates,workoutTemplates,logs,weights,settings,strength]=await Promise.all(['foods','exercises','mealTemplates','workoutTemplates','dayLogs','weights','settings','strengthLogs'].map(s=>DB.all(s)));
  Object.assign(state,{foods,exercises,mealTemplates,workoutTemplates,logs,weights,strength,settings:settings[0]||defaults});
}
function migrateV2(){
  if(localStorage.getItem('mission68-v3-migrated')) return;
  try{const raw=localStorage.getItem('mission68-state');if(!raw)return;const old=JSON.parse(raw);if(Array.isArray(old.weights)) old.weights.forEach(async w=>{const d=w.date||w.d;if(d&&w.weight||w.w) await DB.put('weights',{id:d,date:d,value:num(w.weight||w.w)})});localStorage.setItem('mission68-v3-migrated','1')}catch(e){}
}
function bindShell(){
  $$('.nav-item').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
  $('#overlay').onclick=closeSheet; $('#quickAdd').onclick=quickAdd;
}
function render(){
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  $$('.view').forEach(v=>v.classList.remove('active')); $('#view-'+state.view).classList.add('active');
  ({today:renderToday,log:renderLog,plan:renderLibrary,insights:renderInsights,settings:renderSettings})[state.view]();
  window.scrollTo({top:0,behavior:'smooth'});
}
function todayLog(){let l=state.logs.find(x=>x.id===dayKey());if(!l){l={id:dayKey(),date:dayKey(),meals:[],waterMl:0,workouts:[],steps:0,note:'',sleepHours:null};state.logs.push(l)}return l}
function calcFood(food,qty){return {kcal:food.kcal*qty,protein:food.protein*qty,carbs:food.carbs*qty,fat:food.fat*qty}}
function totals(log){const t={kcal:0,protein:0,carbs:0,fat:0};(log.meals||[]).forEach(m=>(m.items||[]).forEach(i=>{const f=state.foods.find(x=>x.id===i.foodId);if(f){const c=calcFood(f,num(i.qty));Object.keys(t).forEach(k=>t[k]+=c[k])}}));return t}
function dailyScore(log,t){let parts=[clamp(t.kcal/state.settings.kcalTarget,0,1),clamp(t.protein/state.settings.proteinTarget,0,1),clamp(log.waterMl/state.settings.waterTargetMl,0,1)];if((log.workouts||[]).length)parts.push(1);return Math.round(parts.reduce((a,b)=>a+b,0)/parts.length*100)}
function latestWeight(){return [...state.weights].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)}
function renderToday(){
  const l=todayLog(),t=totals(l),w=latestWeight(),remaining=w?Math.max(0,w.value-state.settings.goalWeight):state.settings.startWeight-state.settings.goalWeight,score=dailyScore(l,t);
  const mealRows=state.mealTemplates.map(m=>{const logged=l.meals.find(x=>x.templateId===m.id);const mt=mealTotal(m);return `<button class="row wide" data-meal="${m.id}"><span class="check ${logged?'done':''}"></span><span class="row-main"><span class="row-title">${esc(m.name)}</span><span class="row-sub">${m.items.length} items · ${esc(m.time||'No time')}</span></span><span class="row-meta">${Math.round(mt.kcal)} kcal<br>${mt.protein.toFixed(1)} g P</span></button>`}).join('');
  $('#view-today').innerHTML=`
    <div class="hero"><div class="date-line">${fmtDate(dayKey())}</div><h2>${score>=80?'A controlled day in progress.':'Build the day one decision at a time.'}</h2><div class="subtle">Current weight ${w?`${w.value.toFixed(1)} kg`:'not logged'} · ${remaining.toFixed(1)} kg remaining</div></div>
    <div class="grid grid-3">
      ${metric('Calories',Math.round(t.kcal),state.settings.kcalTarget,'kcal')}
      ${metric('Protein',t.protein.toFixed(0),state.settings.proteinTarget,'g')}
      ${metric('Water',(l.waterMl/1000).toFixed(1),(state.settings.waterTargetMl/1000).toFixed(1),'L')}
    </div>
    <div class="section"><div class="section-head"><h3>Meals</h3><button class="text-button" id="addMealLog">Add entry</button></div><div class="list">${mealRows||'<div class="empty">Create a meal template in Library.</div>'}</div></div>
    <div class="section"><div class="section-head"><h3>Movement</h3><button class="text-button" id="addWorkoutLog">Log workout</button></div>${todayWorkoutCard(l)}</div>
    <div class="section"><div class="section-head"><h3>Daily details</h3></div><div class="card form-grid"><div class="field-group"><label>WATER, ML</label><input id="waterInput" class="field" type="number" value="${l.waterMl}"></div><div class="field-group"><label>STEPS</label><input id="stepsInput" class="field" type="number" value="${l.steps||0}"></div><div class="field-group full"><label>NOTE</label><textarea id="noteInput" class="field">${esc(l.note||'')}</textarea></div><button id="saveDay" class="primary full">Save daily details</button></div></div>
    <div class="section"><div class="section-head"><h3>Weigh-in</h3></div><div class="card button-row"><input id="weightInput" class="field" style="flex:1" type="number" step="0.1" placeholder="Weight in kg"><button id="saveWeight" class="primary">Log</button></div></div>`;
  $$('[data-meal]').forEach(b=>b.onclick=()=>toggleTemplateMeal(b.dataset.meal));
  $('#addMealLog').onclick=()=>openMealLog(); $('#addWorkoutLog').onclick=()=>openWorkoutLog();
  $('#saveDay').onclick=saveDayDetails; $('#saveWeight').onclick=saveWeight;
}
function metric(label,val,target,unit){const p=clamp(num(val)/num(target),0,1)*100;return `<div class="card metric"><div class="label">${label}</div><div class="value mono">${val} <small>${unit}</small></div><div class="meta">Target ${target} ${unit}</div><div class="progress"><span style="width:${p}%"></span></div></div>`}
function mealTotal(m){const t={kcal:0,protein:0,carbs:0,fat:0};(m.items||[]).forEach(i=>{const f=state.foods.find(x=>x.id===i.foodId);if(f){const c=calcFood(f,i.qty);Object.keys(t).forEach(k=>t[k]+=c[k])}});return t}
function todayWorkoutCard(l){const dow=new Date().getDay();const planned=state.workoutTemplates.find(w=>(w.days||[]).includes(dow));if(!planned)return `<div class="card"><div class="row-title">Recovery or walking day</div><div class="row-sub">Log any movement you complete.</div></div>`;const done=l.workouts?.some(x=>x.templateId===planned.id);return `<button class="row wide" data-workout="${planned.id}"><span class="check ${done?'done':''}"></span><span class="row-main"><span class="row-title">${esc(planned.name)}</span><span class="row-sub">${planned.items.length} exercises</span></span><span class="pill ${done?'positive':''}">${done?'Completed':'Planned'}</span></button>`}
async function toggleTemplateMeal(id){const l=todayLog(),idx=l.meals.findIndex(x=>x.templateId===id);if(idx>=0)l.meals.splice(idx,1);else{const m=state.mealTemplates.find(x=>x.id===id);l.meals.push({id:uid('logmeal'),templateId:id,name:m.name,items:m.items.map(x=>({...x}))})}await saveLog(l);renderToday()}
async function saveLog(l){await DB.put('dayLogs',l);state.logs=state.logs.filter(x=>x.id!==l.id).concat(l)}
async function saveDayDetails(){const l=todayLog();l.waterMl=num($('#waterInput').value);l.steps=num($('#stepsInput').value);l.note=$('#noteInput').value.trim();await saveLog(l);toast('Day saved');renderToday()}
async function saveWeight(){const v=num($('#weightInput').value);if(v<40||v>150)return toast('Enter a valid weight');const x={id:dayKey(),date:dayKey(),value:v};await DB.put('weights',x);state.weights=state.weights.filter(w=>w.id!==x.id).concat(x);toast('Weight logged');renderToday()}
function quickAdd(){openSheet(`<h2>Quick add</h2><div class="list"><button class="row" id="qaFood"><span class="row-main"><span class="row-title">Food entry</span><span class="row-sub">Add food from your database</span></span></button><button class="row" id="qaWater"><span class="row-main"><span class="row-title">250 ml water</span><span class="row-sub">Add one glass to today</span></span></button><button class="row" id="qaWeight"><span class="row-main"><span class="row-title">Weight</span><span class="row-sub">Record a weigh-in</span></span></button></div>`);$('#qaFood').onclick=()=>openMealLog();$('#qaWater').onclick=async()=>{const l=todayLog();l.waterMl+=250;await saveLog(l);closeSheet();renderToday();toast('Water added')};$('#qaWeight').onclick=()=>{closeSheet();$('#weightInput')?.focus()}}
function openMealLog(){
  openSheet(`<h2>Add food entry</h2><p class="sheet-sub">Choose any food from your personal database.</p><div class="form-grid"><div class="field-group full"><label>MEAL NAME</label><input id="lmName" class="field" value="Custom meal"></div><div class="field-group"><label>FOOD</label><select id="lmFood" class="field">${state.foods.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select></div><div class="field-group"><label>QUANTITY</label><input id="lmQty" class="field" type="number" step="0.1" value="1"></div><button id="lmSave" class="primary full">Add to today</button><button id="lmClose" class="secondary full">Cancel</button></div>`);
  $('#lmClose').onclick=closeSheet;$('#lmSave').onclick=async()=>{const l=todayLog();l.meals.push({id:uid('logmeal'),name:$('#lmName').value.trim()||'Custom meal',items:[{foodId:$('#lmFood').value,qty:num($('#lmQty').value,1)}]});await saveLog(l);closeSheet();renderToday();toast('Food added')}
}
function openWorkoutLog(){
  openSheet(`<h2>Log workout</h2><div class="field-group"><label>WORKOUT</label><select id="lwTemplate" class="field">${state.workoutTemplates.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select></div><button id="lwSave" class="primary wide">Mark completed</button>`);
  $('#lwSave').onclick=async()=>{const l=todayLog(),id=$('#lwTemplate').value,w=state.workoutTemplates.find(x=>x.id===id);l.workouts=l.workouts||[];if(!l.workouts.some(x=>x.templateId===id))l.workouts.push({id:uid('worklog'),templateId:id,name:w.name,completedAt:new Date().toISOString()});await saveLog(l);closeSheet();renderToday();toast('Workout logged')}
}
function renderLog(){
  const recent=[...state.logs].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,31);
  $('#view-log').innerHTML=`<div class="hero"><div class="date-line">DAILY RECORD</div><h2>Your recent history.</h2><div class="subtle">Every entry remains editable and exportable.</div></div><div class="calendar">${calendarCells()}</div><div class="section"><div class="section-head"><h3>Recent days</h3></div><div class="list">${recent.map(l=>{const t=totals(l);return `<button class="row wide" data-day="${l.date}"><span class="row-main"><span class="row-title">${fmtDate(l.date,{day:'numeric',month:'short',year:'numeric'})}</span><span class="row-sub">${Math.round(t.kcal)} kcal · ${t.protein.toFixed(0)} g protein · ${(l.waterMl/1000).toFixed(1)} L</span></span><span class="pill">${dailyScore(l,t)}%</span></button>`}).join('')||'<div class="empty">No history yet.</div>'}</div></div>`;
  $$('[data-day]').forEach(b=>b.onclick=()=>showDay(b.dataset.day));
}
function calendarCells(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let out=['S','M','T','W','T','F','S'].map(x=>`<div class="cal-head">${x}</div>`).join('');for(let i=0;i<first;i++)out+='<div></div>';for(let d=1;d<=days;d++){const k=dayKey(new Date(y,m,d)),l=state.logs.find(x=>x.date===k),good=l&&dailyScore(l,totals(l))>=80;out+=`<button class="cal-day ${l?'has':''} ${good?'good':''} ${k===dayKey()?'today':''}" data-day="${k}">${d}</button>`}return out}
function showDay(k){const l=state.logs.find(x=>x.date===k);if(!l)return;const t=totals(l);openSheet(`<h2>${fmtDate(k)}</h2><div class="grid grid-2">${metric('Calories',Math.round(t.kcal),state.settings.kcalTarget,'kcal')}${metric('Protein',t.protein.toFixed(0),state.settings.proteinTarget,'g')}</div><div class="divider"></div><div class="section-label">ENTRIES</div><div class="list" style="margin-top:10px">${(l.meals||[]).map(m=>`<div class="row"><div class="row-main"><div class="row-title">${esc(m.name)}</div><div class="row-sub">${m.items.length} food item(s)</div></div></div>`).join('')||'<div class="empty">No food entries.</div>'}</div><div class="divider"></div><div class="subtle">Water ${(l.waterMl/1000).toFixed(1)} L · Steps ${l.steps||0}</div><p>${esc(l.note||'No note')}</p><button id="closeDay" class="secondary wide">Close</button>`);$('#closeDay').onclick=closeSheet}
function renderLibrary(){
  $('#view-plan').innerHTML=`<div class="hero"><div class="date-line">DYNAMIC LIBRARY</div><h2>Build the plan around your life.</h2><div class="subtle">Foods, meals, exercises and workouts are database records, not hard-coded content.</div></div><div class="tabs"><button class="tab-chip active" data-lib="foods">Foods</button><button class="tab-chip" data-lib="meals">Meals</button><button class="tab-chip" data-lib="exercises">Exercises</button><button class="tab-chip" data-lib="workouts">Workouts</button></div><div id="libraryBody" class="section"></div>`;
  $$('[data-lib]').forEach(b=>b.onclick=()=>{$$('[data-lib]').forEach(x=>x.classList.toggle('active',x===b));renderLibraryBody(b.dataset.lib)});renderLibraryBody('foods')
}
function renderLibraryBody(type){const box=$('#libraryBody');if(type==='foods')box.innerHTML=libraryList('Food database','Add food',state.foods,f=>`${f.kcal} kcal · ${f.protein} g P per ${f.unit}`,'food');if(type==='exercises')box.innerHTML=libraryList('Exercise database','Add exercise',state.exercises,e=>`${e.category} · ${e.equipment}`,'exercise');if(type==='meals')box.innerHTML=libraryList('Meal templates','Add meal',state.mealTemplates,m=>`${m.items.length} items · ${Math.round(mealTotal(m).kcal)} kcal`,'meal');if(type==='workouts')box.innerHTML=libraryList('Workout templates','Add workout',state.workoutTemplates,w=>`${w.items.length} exercises · ${w.days.length} scheduled day(s)`,'workout');$('[data-add]')?.addEventListener('click',()=>openEditor(type.slice(0,-1)));$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.kind,b.dataset.edit))}
function libraryList(title,add,items,sub,kind){return `<div class="section-head"><h3>${title}</h3><button class="text-button" data-add>${add}</button></div><div class="list">${items.map(x=>`<button class="row wide" data-edit="${x.id}" data-kind="${kind}"><span class="row-main"><span class="row-title">${esc(x.name)}</span><span class="row-sub">${esc(sub(x))}</span></span><span class="row-meta">Edit</span></button>`).join('')||'<div class="empty">No records.</div>'}</div>`}
function openEditor(kind,id){
  if(kind==='food')return foodEditor(id);if(kind==='exercise')return exerciseEditor(id);if(kind==='meal')return mealEditor(id);if(kind==='workout')return workoutEditor(id)
}
function foodEditor(id){const x=state.foods.find(v=>v.id===id)||{id:uid('food'),name:'',unit:'100 g',kcal:0,protein:0,carbs:0,fat:0};openSheet(`<h2>${id?'Edit':'Add'} food</h2><div class="form-grid">${field('Name','fName',x.name,'text','full')}${field('Serving unit','fUnit',x.unit)}${field('Calories','fKcal',x.kcal,'number')}${field('Protein, g','fProtein',x.protein,'number')}${field('Carbohydrate, g','fCarbs',x.carbs,'number')}${field('Fat, g','fFat',x.fat,'number')}<button id="fSave" class="primary full">Save food</button>${id?'<button id="fDelete" class="danger-btn full">Delete food</button>':''}</div>`);$('#fSave').onclick=async()=>{Object.assign(x,{name:$('#fName').value.trim(),unit:$('#fUnit').value.trim(),kcal:num($('#fKcal').value),protein:num($('#fProtein').value),carbs:num($('#fCarbs').value),fat:num($('#fFat').value)});if(!x.name)return toast('Name is required');await DB.put('foods',x);await loadAll();closeSheet();renderLibraryBody('foods');toast('Food saved')};if(id)$('#fDelete').onclick=async()=>{await DB.del('foods',id);await loadAll();closeSheet();renderLibraryBody('foods')}}
function exerciseEditor(id){const x=state.exercises.find(v=>v.id===id)||{id:uid('ex'),name:'',equipment:'None',category:'Strength',loadUnit:'kg'};openSheet(`<h2>${id?'Edit':'Add'} exercise</h2><div class="form-grid">${field('Name','eName',x.name,'text','full')}${selectField('Equipment','eEquip',['None','Bodyweight','Dumbbell','Barbell','Resistance band','Bench','Other'],x.equipment)}${selectField('Category','eCat',['Strength','Cardio','Core','Mobility'],x.category)}${selectField('Tracking unit','eUnit',['kg','reps','seconds','minutes','km'],x.loadUnit)}<button id="eSave" class="primary full">Save exercise</button>${id?'<button id="eDelete" class="danger-btn full">Delete exercise</button>':''}</div>`);$('#eSave').onclick=async()=>{Object.assign(x,{name:$('#eName').value.trim(),equipment:$('#eEquip').value,category:$('#eCat').value,loadUnit:$('#eUnit').value});if(!x.name)return toast('Name is required');await DB.put('exercises',x);await loadAll();closeSheet();renderLibraryBody('exercises')};if(id)$('#eDelete').onclick=async()=>{await DB.del('exercises',id);await loadAll();closeSheet();renderLibraryBody('exercises')}}
function mealEditor(id){const x=state.mealTemplates.find(v=>v.id===id)||{id:uid('meal'),name:'',time:'',items:[]};openSheet(`<h2>${id?'Edit':'Add'} meal template</h2><div class="form-grid">${field('Meal name','mName',x.name,'text','full')}${field('Time','mTime',x.time,'time','full')}<div class="full"><div class="section-label">FOODS</div><div id="mItems" class="list" style="margin-top:9px"></div><button id="mAddItem" class="secondary wide" style="margin-top:9px">Add food</button></div><button id="mSave" class="primary full">Save meal</button>${id?'<button id="mDelete" class="danger-btn full">Delete meal</button>':''}</div>`);const renderItems=()=>{$('#mItems').innerHTML=x.items.map((it,i)=>`<div class="row"><select class="field" data-mf="${i}">${state.foods.map(f=>`<option value="${f.id}" ${f.id===it.foodId?'selected':''}>${esc(f.name)}</option>`).join('')}</select><input class="field" style="width:90px" type="number" step="0.1" data-mq="${i}" value="${it.qty}"><button class="text-button" data-mr="${i}">Remove</button></div>`).join('')||'<div class="empty">No food items.</div>';$$('[data-mf]').forEach(el=>el.onchange=()=>x.items[+el.dataset.mf].foodId=el.value);$$('[data-mq]').forEach(el=>el.onchange=()=>x.items[+el.dataset.mq].qty=num(el.value,1));$$('[data-mr]').forEach(el=>el.onclick=()=>{x.items.splice(+el.dataset.mr,1);renderItems()})};renderItems();$('#mAddItem').onclick=()=>{if(!state.foods.length)return toast('Add a food first');x.items.push({foodId:state.foods[0].id,qty:1});renderItems()};$('#mSave').onclick=async()=>{x.name=$('#mName').value.trim();x.time=$('#mTime').value;if(!x.name)return toast('Name is required');await DB.put('mealTemplates',x);await loadAll();closeSheet();renderLibraryBody('meals')};if(id)$('#mDelete').onclick=async()=>{await DB.del('mealTemplates',id);await loadAll();closeSheet();renderLibraryBody('meals')}}
function workoutEditor(id){const x=state.workoutTemplates.find(v=>v.id===id)||{id:uid('workout'),name:'',days:[],items:[]};openSheet(`<h2>${id?'Edit':'Add'} workout template</h2><div class="form-grid">${field('Workout name','wName',x.name,'text','full')}<div class="field-group full"><label>SCHEDULED DAYS</label><div class="button-row">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<button type="button" class="tab-chip ${x.days.includes(i)?'active':''}" data-wday="${i}">${d}</button>`).join('')}</div></div><div class="full"><div class="section-label">EXERCISES</div><div id="wItems" class="list" style="margin-top:9px"></div><button id="wAddItem" class="secondary wide" style="margin-top:9px">Add exercise</button></div><button id="wSave" class="primary full">Save workout</button>${id?'<button id="wDelete" class="danger-btn full">Delete workout</button>':''}</div>`);$$('[data-wday]').forEach(b=>b.onclick=()=>{const d=+b.dataset.wday;x.days=x.days.includes(d)?x.days.filter(v=>v!==d):x.days.concat(d);b.classList.toggle('active')});const renderItems=()=>{$('#wItems').innerHTML=x.items.map((it,i)=>`<div class="row"><div class="row-main"><select class="field" data-we="${i}">${state.exercises.map(e=>`<option value="${e.id}" ${e.id===it.exerciseId?'selected':''}>${esc(e.name)}</option>`).join('')}</select><div class="form-grid" style="margin-top:8px"><input class="field" type="number" data-ws="${i}" value="${it.sets}" placeholder="Sets"><input class="field" type="number" data-wr="${i}" value="${it.reps}" placeholder="Reps"><input class="field full" type="number" step="0.1" data-wl="${i}" value="${it.load}" placeholder="Load"></div></div><button class="text-button" data-wx="${i}">Remove</button></div>`).join('')||'<div class="empty">No exercises.</div>';$$('[data-we]').forEach(el=>el.onchange=()=>x.items[+el.dataset.we].exerciseId=el.value);$$('[data-ws]').forEach(el=>el.onchange=()=>x.items[+el.dataset.ws].sets=num(el.value));$$('[data-wr]').forEach(el=>el.onchange=()=>x.items[+el.dataset.wr].reps=num(el.value));$$('[data-wl]').forEach(el=>el.onchange=()=>x.items[+el.dataset.wl].load=num(el.value));$$('[data-wx]').forEach(el=>el.onclick=()=>{x.items.splice(+el.dataset.wx,1);renderItems()})};renderItems();$('#wAddItem').onclick=()=>{if(!state.exercises.length)return toast('Add an exercise first');x.items.push({exerciseId:state.exercises[0].id,sets:3,reps:10,load:0});renderItems()};$('#wSave').onclick=async()=>{x.name=$('#wName').value.trim();if(!x.name)return toast('Name is required');await DB.put('workoutTemplates',x);await loadAll();closeSheet();renderLibraryBody('workouts')};if(id)$('#wDelete').onclick=async()=>{await DB.del('workoutTemplates',id);await loadAll();closeSheet();renderLibraryBody('workouts')}}
function field(label,id,value,type='text',cls=''){return `<div class="field-group ${cls}"><label>${label.toUpperCase()}</label><input id="${id}" class="field" type="${type}" step="${type==='number'?'0.1':''}" value="${esc(value??'')}"></div>`}
function selectField(label,id,opts,val){return `<div class="field-group"><label>${label.toUpperCase()}</label><select id="${id}" class="field">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></div>`}
function renderInsights(){
  const ws=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date)),latest=ws.at(-1),first=ws[0],delta=latest&&first?latest.value-first.value:0,logs=state.logs.filter(l=>l.date>=dayKey(new Date(Date.now()-6*864e5))),avg=logs.length?Math.round(logs.reduce((a,l)=>a+dailyScore(l,totals(l)),0)/logs.length):0,weeklyLoss=trendRate(ws),eta=latest&&weeklyLoss<0?Math.ceil((latest.value-state.settings.goalWeight)/-weeklyLoss):null;
  $('#view-insights').innerHTML=`<div class="hero"><div class="date-line">PROGRESS ANALYTICS</div><h2>Evidence, not impressions.</h2><div class="subtle">Rolling figures become more useful as your record grows.</div></div><div class="grid grid-2">${simpleMetric('Current weight',latest?latest.value.toFixed(1)+' kg':'—')}${simpleMetric('Total change',latest&&first?(delta>0?'+':'')+delta.toFixed(1)+' kg':'—')}${simpleMetric('7-day adherence',avg+'%')}${simpleMetric('Trend per week',weeklyLoss?weeklyLoss.toFixed(2)+' kg':'—')}</div><div class="section"><div class="section-head"><h3>Weight trend</h3><span class="pill">${eta?`Estimated ${eta} weeks to goal`:'More data needed'}</span></div><div class="chart-wrap"><canvas id="weightChart" width="700" height="280"></canvas></div></div><div class="section"><div class="section-head"><h3>Weekly interpretation</h3></div><div class="card"><div class="row-title">${insightText(avg,weeklyLoss)}</div><div class="row-sub" style="margin-top:8px">Projection is a simple trend estimate, not a medical prediction. Day-to-day weight fluctuations are expected.</div></div></div>`;drawChart(ws)
}
function simpleMetric(k,v){return `<div class="card metric"><div class="label">${k}</div><div class="value mono">${v}</div></div>`}
function trendRate(ws){if(ws.length<2)return 0;const recent=ws.slice(-8),days=(new Date(recent.at(-1).date)-new Date(recent[0].date))/864e5;if(days<=0)return 0;return (recent.at(-1).value-recent[0].value)/days*7}
function insightText(avg,rate){if(avg>=80&&rate<0)return 'Your behaviour and weight trend are moving in the same direction.';if(avg>=80)return 'Adherence is strong. Let the multi-week weight trend catch up before changing the plan.';if(rate<0)return 'Weight is trending down, but consistency can improve to make the result more dependable.';return 'The next useful step is not a harsher target. It is a more complete seven-day record.'}
function drawChart(ws){const c=$('#weightChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#d9dad4';ctx.lineWidth=1;for(let i=1;i<5;i++){const y=i*h/5;ctx.beginPath();ctx.moveTo(42,y);ctx.lineTo(w-15,y);ctx.stroke()}if(ws.length<2){ctx.fillStyle='#6f716b';ctx.font='24px system-ui';ctx.fillText('Log at least two weigh-ins',160,145);return}const vals=ws.map(x=>x.value),min=Math.min(...vals,state.settings.goalWeight)-1,max=Math.max(...vals,state.settings.startWeight)+1;const pts=ws.map((x,i)=>({x:42+i*(w-60)/(ws.length-1),y:15+(max-x.value)*(h-35)/(max-min)}));ctx.strokeStyle='#202421';ctx.lineWidth=4;ctx.lineJoin='round';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle='#202421';pts.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#6f716b';ctx.font='18px system-ui';ctx.fillText(max.toFixed(1)+' kg',4,20);ctx.fillText(min.toFixed(1)+' kg',4,h-7)}
function renderSettings(){const s=state.settings;$('#view-settings').innerHTML=`<div class="hero"><div class="date-line">SYSTEM SETTINGS</div><h2>Targets, ownership and backup.</h2></div><div class="card form-grid">${field('Name','sName',s.name,'text','full')}${field('Start weight','sStart',s.startWeight,'number')}${field('Goal weight','sGoal',s.goalWeight,'number')}${field('Height, cm','sHeight',s.heightCm,'number')}${field('Calories target','sKcal',s.kcalTarget,'number')}${field('Protein target, g','sProtein',s.proteinTarget,'number')}${field('Water target, ml','sWater',s.waterTargetMl,'number')}<button id="saveSettings" class="primary full">Save settings</button></div><div class="section"><div class="section-head"><h3>Data management</h3></div><div class="list"><button class="row wide" id="exportData"><span class="row-main"><span class="row-title">Export complete backup</span><span class="row-sub">JSON file containing every database table</span></span></button><button class="row wide" id="importData"><span class="row-main"><span class="row-title">Import backup</span><span class="row-sub">Replace current records with a Mission 68 backup</span></span></button><button class="row wide" id="csvData"><span class="row-main"><span class="row-title">Export daily summary as CSV</span><span class="row-sub">Suitable for spreadsheets and further analysis</span></span></button><input id="importFile" type="file" accept="application/json" hidden></div></div><div class="section"><div class="card"><div class="section-label">PRIVACY</div><p class="subtle">Mission 68 is local-first. Routine data is stored in this browser through IndexedDB and remains available offline. Export regular backups before clearing browser data or changing devices.</p></div></div>`;$('#saveSettings').onclick=saveSettings;$('#exportData').onclick=exportJSON;$('#csvData').onclick=exportCSV;$('#importData').onclick=()=>$('#importFile').click();$('#importFile').onchange=importJSON}
async function saveSettings(){const s={...state.settings,name:$('#sName').value.trim(),startWeight:num($('#sStart').value),goalWeight:num($('#sGoal').value),heightCm:num($('#sHeight').value),kcalTarget:num($('#sKcal').value),proteinTarget:num($('#sProtein').value),waterTargetMl:num($('#sWater').value)};await DB.put('settings',s);state.settings=s;toast('Settings saved')}
async function exportJSON(){const data={version:3,exportedAt:new Date().toISOString(),stores:{}};for(const s of DB.stores)data.stores[s]=await DB.all(s);download('mission68-backup-'+dayKey()+'.json',JSON.stringify(data,null,2),'application/json')}
function exportCSV(){const rows=[['date','calories','protein_g','carbs_g','fat_g','water_ml','steps','score_percent','weight_kg']];[...state.logs].sort((a,b)=>a.date.localeCompare(b.date)).forEach(l=>{const t=totals(l),w=state.weights.find(x=>x.date===l.date);rows.push([l.date,t.kcal.toFixed(1),t.protein.toFixed(1),t.carbs.toFixed(1),t.fat.toFixed(1),l.waterMl||0,l.steps||0,dailyScore(l,t),w?.value||''])});download('mission68-daily-'+dayKey()+'.csv',rows.map(r=>r.join(',')).join('\n'),'text/csv')}
async function importJSON(e){const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data.stores)throw Error();for(const s of DB.stores){await DB.clear(s);if(Array.isArray(data.stores[s]))await DB.bulkPut(s,data.stores[s])}await loadAll();toast('Backup imported');render()}catch(err){toast('Invalid backup file')}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
boot();
})();
